publicKey:
    dir: classpath:certs/
    files: chat.der,frontend.der

user-service:
    addr: http://lolx-auth.herokuapp.com/

category-service:
    addr: http://lolx-category.herokuapp.com/

notification-service:
  addr: http://lolx-notification.herokuapp.com/

front-service:
  addr: http://lolx-front.herokuapp.com/

private-key:
  path: classpath:private_key.der

spring:
  http:
    multipart:
      maxFileSize: 10MB